src/nimlsppkg/base_protocol.nim

I was having trouble using this in vim/neovim due to some deserializing issue. After digging around for a while I found the offending code seemed to be two newlines after the message. It is working for me now, but please try it yourself in your client to see if it works for you as well!
And thanks for making nim an awesome experience in vim!

FIX: LanguageClient-neovim deserializing issue

---

README.rst

The previously listed `git submodule` command did not work as advertised, doing nothing when executed on a newly cloned nimlsp repository. Instead, the newly proposed command actually clones the Nim repository (as suggested on stackoverflow: https://stackoverflow.com/a/53015726), as confirmed by the following output from git:
C:\prog\nimlsp>git submodule update --init --recursive
Submodule 'src/nimlsppkg/Nim' (https://github.com/nim-lang/Nim.git) registered for path 'src/nimlsppkg/Nim'
Cloning into 'C:/prog/nimlsp/src/nimlsppkg/Nim'...
Submodule path 'src/nimlsppkg/Nim': checked out '5b98afb8a8120b697fac625fd691f3484c328b23'

Readme: fix git submodule clone command

---

src/nimlsp.nim
tests/tnimlsp.nim

On Windows, file URIs look like below:
file:///C:/foo/bar
Just stripping the `file://` prefix from such URIs, as was done
previously, produces strings that are not correct Windows paths, for
example:
/C:/foo/bar
This change removes the spurious "/" prefix from paths on Windows.
Fixes #23.

fix parsing of file URIs on Windows

---

README.rst

README has syntax error.
Json does not have the comment syntax.
I think that you should remove red highlight syntax error.

Change file type of README from json to js.

---

README.rst

Updates the README to make the `.vimrc` configuration work seamlessly on Windows.
* vim can detect the presence of Windows using the `has('win32')` feature query function
* Windows has no `/tmp` directory, instead the `%TEMP%` (or rather `$TEMP` in vimL) environment variable points to the temporary path (which *can* be different for each logon session on Windows)
* `nimble` on Windows will create a Window Command-line script file titled `nimlsp.cmd` into the nimble binary directory, the nimlsp server registration needs to take that into account.

Update README to also support Windows environments

---

src/nimlsp.nim

Create clean PR for this, I confirmed `result.removePrefix "/"` is needed on windows. otherwise`nimsuggest ` will not initialise properly

decodeUrl for getProjectFile

---

src/nimlsp.nim
src/nimlsppkg/baseprotocol.nim
src/nimlsppkg/utfmapping.nim

I've included the compiler output below as a reference:
```
/tmp/nimble_201292/githubcom_PMunchnimlsp/src/nimlsppkg/baseprotocol.nim(4, 24) Warning: inherit from a more precise exception type like ValueError, IOError or OSError. If these don't suit, inherit from CatchableError or Defect. [InheritFromException]
/tmp/nimble_201292/githubcom_PMunchnimlsp/src/nimlsppkg/utfmapping.nim(1, 8) Warning: imported and not used: 'tables' [UnusedImport]
/tmp/nimble_201292/githubcom_PMunchnimlsp/src/nimlsp.nim(165, 8) Warning: use fileExists; existsFile is deprecated [Deprecated]
```

Fix warnings emitted by Nim's v1.4 compiler

---

src/nimlsp.nim

if the resolveProvider default is true,vscode client always request "completion/reslove",this will cause the completion view to keep loading...

change resolveProvider default value to false

---

README.rst
src/nimlsp.nim

I've enabled basic support for signatureHelp:
It could definitely be improved; there are a couple of things I tried to add but couldn't get to work:
* set `SignatureHelp.activeParameter`
* I got an ugly hack working to populate `SignatureInformation.parameters` using regex but ultimately could not find an easy way to get the index of the current parameter.
* get signature help to trigger with Nim's command syntax (` ` and `:`)
* Not sure if this was a limitation of the vim plugins I was using.

Enable signatureHelp

---

src/nimlsp.nim
src/nimlsppkg/baseprotocol.nim

hmm , as changed main branch github can't not really diff like other tools, please just check async part.

async server

---

src/nimlsp.nim
src/nimlsppkg/baseprotocol.nim
src/nimlsppkg/logger.nim

- Bump version
- async server (#109)
- Minor style-fixes
- use file logger

useFileLogger

---

src/nimlsp.nim

This PR implements the fix for the issue discussed in #87.
This issue made the "Reference" feature and the "Goto Definition" features not work on Windows.
This affected Sublime Text and CudaText and maybe other editors.
Credit goes to veksha for suggesting this patch.
`nimble test` works.

Add a fix for windows for proper URI handling (#87)

---

.gitignore
nimlsp.nimble
src/config.nims
src/nimlsp.nim
src/nimlsppkg/baseprotocol.nim
src/nimlsppkg/logger.nim
src/nimlsppkg/messages.nim
src/nimlsppkg/suggestlib.nim
src/nimlsppkg/utfmapping.nim
tests/test_messages2.nim
tests/tnimlsp.nim

fix https://github.com/PMunch/nimlsp/issues/121

windows compatibility through multisync

---

src/nimlsppkg/baseprotocol.nim

The error is emitted when running `nimble debug [-d:debugLogging]`

Fix `infoLog` not defined

---

src/nimlsp.nim

The issue is that an infinite loop occurs in every run of nimlsp following this commit in Nim: 23e0160af283bb0bb573a86145e6c1c792780d49.
`splitFile` has changed behavior on Windows. `splitFile("D:").dir` now returns "D:" instead of "". This behavior is now consistent with Linux's `splitFile` where `splitFile("/").dir` returns `/`.
The condition `path != "/"` in nimlsp code assumes that that the root component is a Linux root component. This adds support for Windows roots by using the platform-independent `isRootDir` proc. `path.len > 0` is removed because `""` counts as a root dir.
Fixes: #140

Fix infinite loop regression on Windows

---

src/nimlsp.nim

Just a trivial change to make overload details similar to the way the C# LSP does it:
C#:
Nim:
This gives a better idea of signatures for overloads when quickly scanning the completion list.

Show first signature if overload exists

---

src/nimlsp.nim

When building nimlsp in a sandbox (before installing it on a system) the
temporary directory might be different. In my case I was building nimlsp
with Nix which caused nimlsp to hardcode `/build/nimlsp` as storage
directory. That directory only exists within the build sandbox and even
if it would exist outside of the sandbox it wouldn't be writable by the
average user.
Side note: This is the very first Nim code I've ever "written".

Ensure the storage directory is calculated during runtime

---

src/nimlsp.nim
src/nimlsppkg/messages.nim
tests/test_messages2.nim
tests/tnimlsp.nim

Fixes about a million warnings like this by running `nimpretty`:
```
/Users/marcus/Source/nimlsp/src/nimlsppkg/messages.nim(592, 25) Warning: Number of spaces around '?:' is not consistent [Spacing]
```
as well as:
```
/Users/marcus/Source/nimlsp/src/nimlsppkg/messages.nim(2, 8) Warning: imported and not used: 'messageenums' [UnusedImport]
/Users/marcus/Source/nimlsp/tests/tnimlsp.nim(1, 11) Warning: imported and not used: 'streams' [UnusedImport]
/Users/marcus/Source/nimlsp/tests/tnimlsp.nim(1, 11) Warning: imported and not used: 'asyncfile' [UnusedImport]
````

Fix various warnings seen when running nimble test on 1.6.10

---

src/nimlsp.nim

Currently, results in vscode are shown alphabetic which complete is a waste considering nimsuggest goes to the trouble of sorting suggestions.
This sets sortext which tells the client that the server would like the items in a particular order

Forced ordering of responses to prevent them from ending up alphabetical

---

README.rst

When building with v2 of the language repo, nimsuggest wants to import `sha1` from under the 'dist/' directory: https://github.com/nim-lang/Nim/blob/v2.0.0/nimsuggest/nimsuggest.nim#L19 That directory is generated in the course of building the main Nim repository; without it `nimsuggest` will not build and therefore building `nimlsp` will also fail.

Add build note for Nim 2.0.0

---

README.rst

Eglot is now built in to Emacs and is the other main LSP client implementation besides `lsp-mode`.

Add Emacs Eglot config to README

---

README.rst

* NimLime no longer interferes.
* Update syntax name.
* Add instructions to enable syntax highlighting in popups.

Update Sublime Text's instructions

---

src/nimlsppkg/logger.nim

The logging templates in `logger` reference procs like `error`, `info`, `warn` etc. from the `logging` module. These are implicitly bound, as they have exactly 1 overload in the scope of the template definitions (https://github.com/nim-lang/Nim/issues/11184).
If this behavior of Nim or the context in `logger` were to change, these would start preferring procs like `macros.error` instead and cause issues. Explicitly binding them keeps the current behavior consistent.
An alternative would be to directly call `logging.error join(args)` etc.

Explicitly bind logging procs in templates
